from __future__ import annotations

import argparse
import os

import torch
import yaml
from diffusers import AutoencoderKL, DDIMScheduler

from color_map import get_hardware_conditions
from detect import get_device, get_hardware_profile
from model import HardwareAwareDiT, load_pretrained_transformer
from utils import (
    benchmark_device,
    decode_latents,
    ensure_dir,
    get_resolution,
    get_steps,
    pick_jitter,
    seed_everything,
    tensor_to_pil,
)

# Pre-computed T5 color embeddings (generated by colorEmb_cache/cache_generate.py)
COLOR_CACHE_PATH = os.path.join(os.path.dirname(__file__), "colorEmb_cache", "brand_color_embeddings.pt")
_FALLBACK_BRAND = "unknown"


def load_config(path: str) -> dict:
    with open(path, "r", encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def load_checkpoint(model: HardwareAwareDiT, path: str) -> None:
    if not path or not os.path.exists(path):
        return
    payload = torch.load(path, map_location="cpu")
    state = payload["hardware_eye"] if "hardware_eye" in payload else payload
    model.load_trainable_state(state)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", default="config.yaml")
    parser.add_argument("--checkpoint", default=None)
    args = parser.parse_args()

    config = load_config(args.config)
    seed_everything(int(config["generate"]["seed"]))

    device = get_device()
    transformer = load_pretrained_transformer(config["model"]["pretrained_transformer"])
    model = HardwareAwareDiT(transformer).to(device)

    checkpoint_path = args.checkpoint or config["model"].get("checkpoint")
    load_checkpoint(model, checkpoint_path)
    model.eval()

    vae = AutoencoderKL.from_pretrained(config["model"]["vae_path"]).to(device)
    vae.eval()

    cond_dim = model.film_gamma.in_features
    perf_index, avg_time = benchmark_device(
        model,
        device,
        ref_time=float(config["benchmark"]["ref_time"]),
        repeats=int(config["benchmark"]["repeats"]),
        steps=int(config["benchmark"]["steps"]),
        latent_size=int(config["benchmark"]["latent_size"]),
        cond_dim=cond_dim,
    )

    res = get_resolution(
        perf_index,
        min_res=int(config["generate"]["min_res"]),
        max_res=int(config["generate"]["max_res"]),
    )
    steps = get_steps(
        perf_index,
        min_steps=int(config["generate"]["min_steps"]),
        max_steps=int(config["generate"]["max_steps"]),
    )
    jitter = pick_jitter(
        perf_index,
        low=float(config["generate"]["jitter_low"]),
        mid=float(config["generate"]["jitter_mid"]),
        high=float(config["generate"]["jitter_high"]),
    )

    hw_profile = get_hardware_profile()
    conditions_dict = get_hardware_conditions(hw_profile, perf_index, jitter=jitter)
    perf_tensor = torch.tensor([perf_index], device=device)

    # Load pre-computed T5 color embedding cache
    color_cache = torch.load(COLOR_CACHE_PATH, map_location="cpu")

    # Blend CPU + GPU color embeddings: 4:6 ratio
    cpu_brand = conditions_dict.get("cpu_brand", _FALLBACK_BRAND)
    gpu_brand = conditions_dict.get("gpu_brand")
    cpu_emb = color_cache.get(cpu_brand, color_cache[_FALLBACK_BRAND])

    if gpu_brand:
        gpu_emb = color_cache.get(gpu_brand, color_cache[_FALLBACK_BRAND])
        color_emb = 0.4 * cpu_emb + 0.6 * gpu_emb
    else:
        color_emb = cpu_emb

    cond = model.cond_encoder([conditions_dict], perf_tensor)

    scheduler = DDIMScheduler(num_train_timesteps=int(config["diffusion"]["train_timesteps"]))
    scheduler.set_timesteps(steps, device=device)

    height = res // 8
    width = res // 8
    latents = torch.randn(1, 4, height, width, device=device)

    with torch.no_grad():
        for t in scheduler.timesteps:
            timestep = torch.tensor([t], device=device)
            noise_pred = model.forward_with_cond(latents, timestep, cond, color_emb)
            latents = scheduler.step(noise_pred, t, latents).prev_sample

    images = decode_latents(vae, latents)
    output_dir = config["generate"]["output_dir"]
    ensure_dir(output_dir)
    file_name = f"hardware_eye_perf_{perf_index:.2f}_time_{avg_time:.2f}s.png"
    output_path = os.path.join(output_dir, file_name)
    tensor_to_pil(images)[0].save(output_path)

    print(f"Hardware profile: {hw_profile}")
    print(f"Perf index: {perf_index:.3f} (bench {avg_time:.3f}s)")
    print(f"Resolution: {res}x{res}, steps: {steps}, jitter: {jitter:.3f}")
    print(f"Saved: {output_path}")


if __name__ == "__main__":
    main()
