from __future__ import annotations

import argparse
import os
import random
import re
from typing import Any

import numpy as np
import torch
import yaml
from diffusers import PixArtSigmaPipeline, Transformer2DModel, AutoencoderKL, DPMSolverMultistepScheduler
from PIL import Image

from color_map import get_hardware_conditions
from detect import get_device, get_hardware_profile
from utils import benchmark_device, ensure_dir, get_resolution, get_steps, pick_jitter, seed_everything

BASE_DIR = os.path.dirname(__file__)
DEFAULT_PIPELINE_PATH = os.path.join(BASE_DIR, "models", "pixart_sigma")
CACHE_PATH     = os.path.join(BASE_DIR, "colorEmb_cache", "brand_style_embeds.pt")
FALLBACK_BRAND = "unknown"


def load_config(path: str) -> dict[str, Any]:
    with open(path, "r", encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def resolve_path(path: str | None, base_dir: str) -> str | None:
    if not path:
        return None
    return path if os.path.isabs(path) else os.path.join(base_dir, path)


def safe_name(value: str | None) -> str:
    value = value or "none"
    return re.sub(r"[^a-zA-Z0-9_.-]+", "-", value).strip("-").lower() or "unknown"


def choose_seed(config_seed: Any, cli_seed: int | None) -> int:
    if cli_seed is not None:
        return cli_seed
    if config_seed is not None:
        return int(config_seed)
    return random.SystemRandom().randint(0, 2**31 - 1)


def load_prompt_cache() -> dict[str, dict[str, torch.Tensor]]:
    """Load pre-computed brand embeddings (generated by cache_generate.py)."""
    if not os.path.exists(CACHE_PATH):
        raise FileNotFoundError(
            f"Cache not found at {CACHE_PATH}. "
            "Run: python colorEmb_cache/cache_generate.py"
        )
    return torch.load(CACHE_PATH, map_location="cpu", weights_only=False)


def apply_brand_color_grade(image: Image.Image, color_rgb: torch.Tensor, strength: float) -> Image.Image:
    if strength <= 0:
        return image

    arr = np.asarray(image.convert("RGB"), dtype=np.float32) / 255.0
    target = color_rgb.detach().cpu().numpy().astype(np.float32).clip(0, 1)
    target = target / max(float(target.mean()), 1e-6)
    current = arr.mean(axis=(0, 1))
    current = current / max(float(current.mean()), 1e-6)
    scale = target / np.clip(current, 1e-3, None)
    graded = arr * ((1.0 - strength) + strength * scale.reshape(1, 1, 3))
    graded = np.clip(graded, 0, 1)
    return Image.fromarray((graded * 255).round().astype("uint8"))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", default="config.yaml")
    parser.add_argument("--seed", type=int, default=None)
    parser.add_argument("--steps", type=int, default=None)
    parser.add_argument("--guidance-scale", type=float, default=4.5)
    parser.add_argument("--color-token-strength", type=float, default=0.18)
    parser.add_argument("--color-grade-strength", type=float, default=0.22)
    parser.add_argument("--max-sequence-length", type=int, default=300)
    args = parser.parse_args()

    config_path = os.path.abspath(args.config)
    config_dir = os.path.dirname(config_path)
    config = load_config(config_path)

    seed = choose_seed(config["generate"].get("seed"), args.seed)
    seed_everything(seed)

    device = get_device()
    dtype = torch.float16 if device.type == "cuda" else torch.float32
    pipeline_path = resolve_path(
        config["model"].get("pipeline_path", DEFAULT_PIPELINE_PATH),
        config_dir,
    )

    pipe = PixArtSigmaPipeline(
        transformer=Transformer2DModel.from_pretrained(
            os.path.join(pipeline_path, "transformer"), torch_dtype=dtype
        ),
        vae=AutoencoderKL.from_pretrained(
            os.path.join(pipeline_path, "vae"), torch_dtype=dtype
        ),
        scheduler=DPMSolverMultistepScheduler.from_pretrained(
            os.path.join(pipeline_path, "scheduler")
        ),
        text_encoder=None,   # not needed — we pass prompt_embeds directly
        tokenizer=None,      # not needed
    )
    pipe = pipe.to(device)
    pipe.set_progress_bar_config(disable=False)

    perf_index, avg_time = benchmark_device(
        pipe.transformer,
        device,
        ref_time=float(config["benchmark"]["ref_time"]),
        repeats=int(config["benchmark"]["repeats"]),
        steps=int(config["benchmark"]["steps"]),
    )

    res = get_resolution(
        perf_index,
        min_res=int(config["generate"]["min_res"]),
        max_res=int(config["generate"]["max_res"]),
    )
    steps = args.steps if args.steps is not None else get_steps(
        perf_index,
        min_steps=int(config["generate"]["min_steps"]),
        max_steps=int(config["generate"]["max_steps"]),
    )
    if steps <= 0:
        raise ValueError("--steps must be greater than 0")

    jitter = pick_jitter(
        perf_index,
        low=float(config["generate"]["jitter_low"]),
        mid=float(config["generate"]["jitter_mid"]),
        high=float(config["generate"]["jitter_high"]),
    )

    hw_profile = get_hardware_profile()
    conditions = get_hardware_conditions(hw_profile, perf_index, jitter=jitter)
    cpu_brand = conditions.get("cpu_brand", FALLBACK_BRAND)
    gpu_brand = conditions.get("gpu_brand", FALLBACK_BRAND)
    color_rgb = conditions["color_rgb"]

    # Load pre-computed prompt embeddings from cache (generated by cache_generate.py)
    prompt_cache = load_prompt_cache()
    neg = prompt_cache["_negative_"]
    cpu_brand = cpu_brand if cpu_brand in prompt_cache else FALLBACK_BRAND
    gpu_brand = gpu_brand if gpu_brand in prompt_cache else FALLBACK_BRAND
    
    cpu_entry = prompt_cache.get(cpu_brand, prompt_cache[FALLBACK_BRAND])
    gpu_entry = prompt_cache.get(gpu_brand) if gpu_brand else None

    if gpu_entry is not None:
        # Blend CPU:GPU = 4:6
        brand_entry = {
            "prompt_embeds": 0.4 * cpu_entry["prompt_embeds"] + 0.6 * gpu_entry["prompt_embeds"],
            "prompt_mask": (cpu_entry["prompt_mask"] + gpu_entry["prompt_mask"]).clamp(0, 1),
        }
        print(f"Blended prompt embeds: cpu={cpu_brand}(0.4) + gpu={gpu_brand}(0.6)")
    else:
        brand_entry = cpu_entry
        print(f"Using prompt embeds for brand: {cpu_brand}")

    prompt_embeds   = brand_entry["prompt_embeds"].to(device=device, dtype=dtype)
    prompt_mask     = brand_entry["prompt_mask"].to(device=device)
    negative_embeds = neg["prompt_embeds"].to(device=device, dtype=dtype)
    negative_mask   = neg["prompt_mask"].to(device=device)
    print("Loaded cached prompt embeds for brand")

    generator = torch.Generator(device=device).manual_seed(seed)
    result = pipe(
        prompt=None,
        negative_prompt=None,
        prompt_embeds=prompt_embeds,
        prompt_attention_mask=prompt_mask,
        negative_prompt_embeds=negative_embeds,
        negative_prompt_attention_mask=negative_mask,
        num_inference_steps=steps,
        guidance_scale=args.guidance_scale,
        height=res,
        width=res,
        generator=generator,
        output_type="pil",
    )
    ''' 
    image = apply_brand_color_grade(result.images[0], color_rgb, args.color_grade_strength)
    '''
    image = result.images[0]

    output_dir = resolve_path(config["generate"]["output_dir"], config_dir)
    ensure_dir(output_dir)
    file_name = (
        f"hardware_eye_{safe_name(cpu_brand)}_{safe_name(gpu_brand)}"
        f"_seed_{seed}_steps_{steps}_cfg_{args.guidance_scale:.1f}_perf_{perf_index:.2f}.png"
    )
    output_path = os.path.join(output_dir, file_name)
    image.save(output_path)

    print(f"Hardware profile: {hw_profile}")
    print(f"Color brands: cpu={cpu_brand}, gpu={gpu_brand or 'none'}, rgb={color_rgb.tolist()}")
    print("Generation path: native PixArtSigmaPipeline with empty-prompt scene prior")
    print(
        "Hardware injection: performance->resolution/steps, "
        f"color token strength={args.color_token_strength:.2f}, "
        f"color grade strength={args.color_grade_strength:.2f}"
    )
    print(f"Prompt embeds: {tuple(prompt_embeds.shape)}, attention mask: {tuple(prompt_mask.shape)}")
    print(f"Perf index: {perf_index:.3f} (bench {avg_time:.3f}s)")
    print(f"Resolution: {res}x{res}, steps: {steps}, seed: {seed}, jitter: {jitter:.3f}")
    print(f"Saved: {output_path}")


if __name__ == "__main__":
    main()
